### ISSUE TITLE
您好，关于构造同义句组的问题

### ISSUE THREAD

**Issue by song-ting** [zhpmatrix/margin-loss-for-sentence-similarity#2]
- 最近也看了苏剑林关于 am softmax的文章
- 看了一下新浪爱问，发现每个问题只是有一些“类似问题”，请问您是通过这个“类似问题”来构造同义句组的么？这样会不会导致脏数据的问题？
- 我试过在LCQMC数据集上通过语义传递和并查集构造同义句组，但是因为数据集里的脏数据，导致模型效果不好？
- 请问您能分享您构造同义句组的方法或者数据集么，非常感谢！！！

**Comment by zhpmatrix** [comment]
1.可以看一下“类似问题”的质量怎样，不过我已经不太记得爬的什么了。

2.脏数据会有，比例大概可以控制在一定的范围内应该就可以吧。

3.相似性传递会引入一些noise，正因为此，没有通过这种手段去构造数据。

4.数据集暂时不分享，希望理解。无论在新浪爱问，还是其他平台，估计都可以构建。

**Comment by song-ting** [comment]
> 1.可以看一下“类似问题”的质量怎样，不过我已经不太记得爬的什么了。
> 
> 2.脏数据会有，比例大概可以控制在一定的范围内应该就可以吧。
> 
> 3.相似性传递会引入一些noise，正因为此，没有通过这种手段去构造数据。
> 
> 4.数据集暂时不分享，希望理解。无论在新浪爱问，还是其他平台，估计都可以构建。

好的，多谢！！
